import Head from "next/head";
import dynamic from "next/dynamic";
import {useIntl} from "react-intl";

const Landing = dynamic(() => import("@/Components/Layout/Landing"));

export default function Home() {
    const intl = useIntl();
  return (
      <Landing>
          <Head>
              <title>{intl.formatMessage({ id: "main.title" })}</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/public/favicon.ico" />
          </Head>
      </Landing>
  );
}
